=== Islandora/documentation/xsd/collection_policy.xsd
<xsd:schema xmlns="http://www.islandora.ca" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.islandora.ca" elementFormDefault="qualified" >
    <xsd:annotation>
        <xsd:documentation xml:lang="en">
      Islandora Collection Policy Schema
      Islandora, Robertson Library, University of Prince Edward Island, 550 University Ave., Charlottetown, Prince Edward Island
        </xsd:documentation>
    </xsd:annotation>
  
    <xsd:element name="collection_policy" type="collection_policyType"/>
    <xsd:complexType name="collection_policyType">
        <xsd:all>
            <xsd:element name="content_models" type="content_modelsType"/>
            <xsd:element name="search_terms" type="search_termsType"/>
            <xsd:element name="relationship" type="xsd:string"/>
            <xsd:element name="staging_area" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:all>
        <xsd:attribute name="name" type="xsd:normalizedString" use="required"/>
    </xsd:complexType>
  
    <xsd:complexType name="content_modelsType">
        <xsd:sequence>
            <xsd:element name="content_model" type="content_modelType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
  
    <xsd:complexType name="content_modelType">
        <xsd:attribute name="name" type="xsd:normalizedString" use="required"/>
        <xsd:attribute name="dsid" type="xsd:normalizedString" use="required"/>
        <xsd:attribute name="namespace" type="xsd:normalizedString" use="required"/>
        <xsd:attribute name="pid" type="xsd:normalizedString" use="required"/>
    </xsd:complexType>
  
    <xsd:complexType name="search_termsType">
        <xsd:sequence>
            <xsd:element name="term" type="termType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
  
    <xsd:complexType name="termType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="field" type="xsd:string" use="optional"/>
                <xsd:attribute name="default" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== Islandora/documentation/plugins/islandora_newspaper/newspapers_collection_policy.xml
<collection_policy xmlns="http://www.islandora.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="" xsi:schemaLocation="http://www.islandora.ca http://syn.lib.umanitoba.ca/collection_policy.xsd">
    <content_models>
        <content_model dsid="ISLANDORACM" name="Newspaper" namespace="islandora" pid="newspapers:issueCModel"></content_model>
    </content_models>
    <search_terms>
        <term field="dc.title">dc.title</term>
        <term field="dc.creator">dc.creator</term>
        <term default="true" field="dc.description">dc.description</term>
        <term field="dc.date">dc.date</term>
        <term field="dc.identifier">dc.identifier</term>
        <term field="dc.language">dc.language</term>
        <term field="dc.publisher">dc.publisher</term>
        <term field="dc.rights">dc.rights</term>
        <term field="dc.subject">dc.subject</term>
        <term field="dc.relation">dc.relation</term>
        <term field="dcterms.temporal">dcterms.temporal</term>
        <term field="dcterms.spatial">dcterms.spatial</term>
        <term field="fgs.DS.first.text">Full Text</term>
    </search_terms>
    <relationship>isMemberOfCollection</relationship>
</collection_policy>

=== Islandora/documentation/collection_policies/JPG-COLLECTION POLICY.xml
<?xml version="1.0" encoding="utf-8"?> <collection_policy xmlns="http://www.islandora.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="" xsi:schemaLocation="http://www.islandora.ca http://syn.lib.umanitoba.ca/collection_policy.xsd"> <content_models> <content_model name="STANDARD_JPEG" dsid="ISLANDORACM" namespace="demo:Smiley" pid="demo:DualResImage"/> </content_models> <search_terms> <term field="dc.title">dc.title</term> <term field="dc.creator">dc.creator</term> <term field="dc.description" default="true">dc.description</term> <term field="dc.date">dc.date</term> <term field="dc.identifier">dc.identifier</term> <term field="dc.language">dc.language</term> <term field="dc.publisher">dc.publisher</term> <term field="dc.rights">dc.rights</term> <term field="dc.subject">dc.subject</term> <term field="dc.relation">dc.relation</term> <term field="dcterms.temporal">dcterms.temporal</term> <term field="dcterms.spatial">dcterms.spatial</term> <term field="fgs.DS.first.text">Full Text</term> </search_terms> <relationship>isMemberOf</relationship> </collection_policy>
